"""Generate detailed export-support documentation from the support matrix.

The README landing page is curated by hand (detection-first HTML table plus
foldable extras). The full family x task x format matrix lives only in
``docs/export_support.md`` and is regenerated by this tool.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


# Repository-owned paths are anchored to this script's location so the tool
# works no matter which directory it is invoked from.
REPO_ROOT = Path(__file__).resolve().parents[1]
INVENTORY_PATH = REPO_ROOT / "reports" / "export_inventory.json"
DOCS_PATH = REPO_ROOT / "docs" / "export_support.md"
MARKERS = {"validated": "✓", "experimental": "exp", "blocked": ""}


def _rows() -> tuple[list[str], list[str], list[str]]:
    from libreyolo.export.support import EXPORT_FORMATS, get_support

    if not INVENTORY_PATH.exists():
        raise FileNotFoundError(
            f"Canonical model inventory is missing: {INVENTORY_PATH}. "
            "Run tools/dump_model_inventory.py in the fully provisioned environment."
        )
    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))

    header = ["Family", "Task", *EXPORT_FORMATS]
    rows = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(["---", "---", *(["---:"] * len(EXPORT_FORMATS))]) + " |",
    ]
    validated_constraints = []
    blocked = []
    for family, metadata in inventory.items():
        for task in metadata["tasks"]:
            entries = [get_support(family, task, fmt) for fmt in EXPORT_FORMATS]
            rows.append(
                "| "
                + " | ".join(
                    [family, task, *(MARKERS[entry.tier] for entry in entries)]
                )
                + " |"
            )
            for fmt, entry in zip(EXPORT_FORMATS, entries):
                if entry.tier == "validated" and entry.constraint:
                    detail = entry.constraint
                    if fmt == "coreml" and entry.reason:
                        detail = f"{entry.reason} {detail}"
                    validated_constraints.append(
                        f"- `{family}` / `{task}` / `{fmt}`: {detail}"
                    )
                if entry.tier == "blocked":
                    blocked.append(f"- `{family}` / `{task}` / `{fmt}`: {entry.reason}")
    return rows, validated_constraints, blocked


def _checkpoint_gates() -> list[str]:
    from libreyolo.export.support import CHECKPOINT_GATES

    return [
        f"- `{family}` / `{task}`: {reason}"
        for (family, task), reason in sorted(CHECKPOINT_GATES.items())
    ]


def _experimental_constraints() -> list[str]:
    from libreyolo.export.support import EXPORT_FORMATS, get_support

    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))
    constraints = []
    for family, metadata in inventory.items():
        for task in metadata["tasks"]:
            for fmt in EXPORT_FORMATS:
                entry = get_support(family, task, fmt)
                if entry.tier == "experimental" and entry.constraint:
                    constraints.append(
                        f"- `{family}` / `{task}` / `{fmt}`: {entry.constraint}"
                    )
    return constraints


def render_docs() -> str:
    rows, validated_constraints, blocked = _rows()
    checkpoint_gates = _checkpoint_gates()
    experimental_constraints = _experimental_constraints()
    return "\n".join(
        [
            "# Export support",
            "",
            "This document is generated from `libreyolo/export/support.py`.",
            "Do not edit the matrix by hand.",
            "",
            "`✓` means parity-validated, `exp` means conversion is available without a",
            "numeric parity guarantee, and an empty cell is blocked in preflight.",
            "",
            *rows,
            "",
            "## Core ML validation scope",
            "",
            "A Core ML check mark applies only to the exact checkpoint, canvas,",
            "precision, graph specializations (including frozen class count or",
            "prompt bound where applicable), compute-unit profile, and reference",
            "graph named below.",
            "Candidate recipes and promoted profiles are machine-readable in",
            "`libreyolo/export/coreml_profiles.py`. A check mark records the",
            "historical parity scope below; it does not by itself create a",
            "runtime profile. Execution-profile v2 requires fresh source, final",
            "deployment-ABI, and evidence identities. At v2 adoption all legacy",
            "profiles were demoted, so `compute_units='validated'` fails closed",
            "until an exact candidate is re-exported and replayed on Apple",
            "hardware under the v2 campaign.",
            "Unless a row explicitly records a public-path gate, validation proves",
            "saved-artifact parity with the exporter-prepared graph, not application",
            "preprocessing/postprocessing, task accuracy, arbitrary geometry, every",
            "model size, Neural Engine placement, or device performance.",
            "",
            "A Core ML `exp` row either lacks saved-package numeric parity on",
            "Apple hardware or retains historical parity that is awaiting a",
            "fresh execution-profile-v2 replay; its constraint states which.",
            "",
            "## Parity thresholds",
            "",
            "- Core ML raw-output gates: maximum relative error 3e-4, minimum",
            "  relative output sensitivity 1e-6, and at least 100x",
            "  sensitivity-to-error margin, unless a narrower row says otherwise.",
            "- Core ML public detection and OBB gates require nonempty equal counts,",
            "  exact classes, deterministic repeats, matched box IoU at least 0.95,",
            "  and maximum absolute score error at most 0.01 unless a row records",
            "  a narrower gate.",
            "- Core ML public segmentation and panoptic gates use one whole-instance",
            "  or whole-segment assignment, deterministic repeats, box IoU at least",
            "  0.95 where applicable, mask IoU at least 0.98, and maximum absolute",
            "  score error at most 0.01.",
            "- Core ML public pose gates preserve the detection-to-keypoint row",
            "  assignment, require box IoU at least 0.995, maximum absolute score",
            "  error at most 0.005, keypoint XY error at most 0.5 source pixel, and",
            "  keypoint-confidence error at most 0.005.",
            "- Core ML public classification gates require maximum probability error",
            "  at most 5e-4, equal top-1/top-5 classes, and deterministic repeats.",
            "- Core ML public semantic gates require global pixel agreement at least",
            "  0.99, the exact predicted class set, per-class mask IoU at least 0.95,",
            "  and deterministic repeats.",
            "- Experimental depth, restoration, and point gates are described by",
            "  their row constraints only after their hardened Apple reruns pass.",
            "",
            "## Validated constraints",
            "",
            "A check mark applies only under any constraint listed here.",
            "",
            *validated_constraints,
            "",
            "## Experimental constraints",
            "",
            "Experimental rows may be narrower than the family-wide size surface.",
            "",
            *experimental_constraints,
            "",
            "## Checkpoint and artifact gates",
            "",
            "These notices are independent of technical export status. A family may",
            "accept user-trained weights even when a published checkpoint is restricted.",
            "",
            *checkpoint_gates,
            "",
            "## Blocked combinations",
            "",
            *blocked,
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    docs_path = DOCS_PATH
    docs = render_docs()
    if args.check:
        if not docs_path.exists() or docs_path.read_text(encoding="utf-8") != docs:
            raise SystemExit(f"Generated export docs are stale: {docs_path}")
        return
    docs_path.write_text(docs, encoding="utf-8")


if __name__ == "__main__":
    main()
