"""Generate detailed export-support documentation from the support matrix.

The README landing page is curated by hand (detection-first HTML table plus
foldable extras). The full family x task x format matrix lives only in
``docs/export_support.md`` and is regenerated by this tool.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


# Repository-owned paths are anchored to this script's location so the tool
# works no matter which directory it is invoked from.
REPO_ROOT = Path(__file__).resolve().parents[1]
INVENTORY_PATH = REPO_ROOT / "reports" / "export_inventory.json"
DOCS_PATH = REPO_ROOT / "docs" / "export_support.md"
MARKERS = {"validated": "✓", "experimental": "exp", "blocked": ""}


def _rows() -> tuple[list[str], list[str], list[str]]:
    from libreyolo.export.support import EXPORT_FORMATS, get_support

    if not INVENTORY_PATH.exists():
        raise FileNotFoundError(
            f"Canonical model inventory is missing: {INVENTORY_PATH}. "
            "Run tools/dump_model_inventory.py in the fully provisioned environment."
        )
    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))

    header = ["Family", "Task", *EXPORT_FORMATS]
    rows = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(["---", "---", *(["---:"] * len(EXPORT_FORMATS))]) + " |",
    ]
    validated_constraints = []
    blocked = []
    for family, metadata in inventory.items():
        for task in metadata["tasks"]:
            entries = [get_support(family, task, fmt) for fmt in EXPORT_FORMATS]
            rows.append(
                "| "
                + " | ".join(
                    [family, task, *(MARKERS[entry.tier] for entry in entries)]
                )
                + " |"
            )
            for fmt, entry in zip(EXPORT_FORMATS, entries):
                if entry.tier == "validated" and entry.constraint:
                    validated_constraints.append(
                        f"- `{family}` / `{task}` / `{fmt}`: {entry.constraint}"
                    )
                if entry.tier == "blocked":
                    blocked.append(f"- `{family}` / `{task}` / `{fmt}`: {entry.reason}")
    return rows, validated_constraints, blocked


def _checkpoint_gates() -> list[str]:
    from libreyolo.export.support import CHECKPOINT_GATES

    return [
        f"- `{family}` / `{task}`: {reason}"
        for (family, task), reason in sorted(CHECKPOINT_GATES.items())
    ]


def _experimental_constraints() -> list[str]:
    from libreyolo.export.support import EXPORT_FORMATS, get_support

    inventory = json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))
    constraints = []
    for family, metadata in inventory.items():
        for task in metadata["tasks"]:
            for fmt in EXPORT_FORMATS:
                entry = get_support(family, task, fmt)
                if entry.tier == "experimental" and entry.constraint:
                    constraints.append(
                        f"- `{family}` / `{task}` / `{fmt}`: {entry.constraint}"
                    )
    return constraints


def render_docs() -> str:
    rows, validated_constraints, blocked = _rows()
    checkpoint_gates = _checkpoint_gates()
    experimental_constraints = _experimental_constraints()
    return "\n".join(
        [
            "# Export support",
            "",
            "This document is generated from `libreyolo/export/support.py`.",
            "Do not edit the matrix by hand.",
            "",
            "`✓` means parity-validated, `exp` means conversion is available without a",
            "numeric parity guarantee, and an empty cell is blocked in preflight.",
            "",
            *rows,
            "",
            "## Core ML experimental profile",
            "",
            "Every Core ML `exp` row is fixed-canvas, batch-one, and raw-output.",
            "It records an implemented conversion path, not macOS runtime parity,",
            "application preprocessing parity, task accuracy, or device performance.",
            "No Core ML row is parity-validated yet.",
            "",
            "## Parity thresholds",
            "",
            "- Detection and OBB: matched box IoU above 0.95 and score MAE below 0.01.",
            "- Segmentation and panoptic: mask IoU above 0.95.",
            "- Pose: keypoint L2 below 2 pixels at native resolution.",
            "- Classification: logits cosine above 0.999 and equal top-1 class.",
            "- Depth and restoration: PSNR above 40 dB against native output.",
            "- Point: peak locations equal within one output cell.",
            "",
            "## Validated constraints",
            "",
            "A check mark applies only under any constraint listed here.",
            "",
            *validated_constraints,
            "",
            "## Experimental constraints",
            "",
            "Experimental rows may be narrower than the family-wide size surface.",
            "",
            *experimental_constraints,
            "",
            "## Checkpoint and artifact gates",
            "",
            "These notices are independent of technical export status. A family may",
            "accept user-trained weights even when a published checkpoint is restricted.",
            "",
            *checkpoint_gates,
            "",
            "## Blocked combinations",
            "",
            *blocked,
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    docs_path = DOCS_PATH
    docs = render_docs()
    if args.check:
        if not docs_path.exists() or docs_path.read_text(encoding="utf-8") != docs:
            raise SystemExit(f"Generated export docs are stale: {docs_path}")
        return
    docs_path.write_text(docs, encoding="utf-8")


if __name__ == "__main__":
    main()
