name: Triage new issues

on:
  issues:
    types: [opened]

jobs:
  triage:
    # Skip auto-triage when the maintainer opens the issue themselves.
    if: github.event.issue.user.login != 'ehxuban11'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh label create triage --color FBCA04 --force -R $GITHUB_REPOSITORY
          gh issue edit ${{ github.event.issue.number }} --add-label triage -R $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ github.token }}
